repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.5"  # Use the ruff version you're working with
    hooks:
    # Check (and apply) import sorting
    -   id: ruff
        args: [check, ., --no-cache, --select, I, --fix, --config=pyproject.toml]
    # Check (and apply) formatting
    -   id: ruff-format
        # entry: ruff format --force-exclude

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict