name: CI Test Suite
on: [push, pull_request]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory
        run: pwd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,docs]"
      - name: Run linter and formatter
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check . --config=pyproject.toml --statistics
          ruff check . --config=pyproject.toml # full error
          # exit-zero treats all errors as warnings.
          ruff check . --config=pyproject.toml --ignore=C901 --exit-zero
      - name: Run tests
        run: pytest --ignore=bibcat/tests/integration/
